services:
  db:
    image: mysql:8.0
    init: true
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./db-procs:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ccny_connect
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      target: dev
    platform: linux/amd64
    init: true
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      SECRET_KEY: 486c53069c1e6b876da5bf5c6e08e7dd
      SECRET_IV: a919d48fcc96fb0d
      DB_HOST: db
      DB_NAME: ccny_connect
      DB_USER: dev
      DB_PASSWORD: dev
