services:
  db:
    image: mysql:8.0
    init: true
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db-procs:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      target: dev
    init: true
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/.next
