INSERT INTO user (email, password_hash, first_name, last_name) VALUES
  ('john.doe@citymail.cuny.edu',       'hashedpassword1',  'John',      'Doe'),
  ('jane.smith@citymail.cuny.edu',     'hashedpassword2',  'Jane',      'Smith'),
  ('michael.jordan@citymail.cuny.edu', 'hashedpassword3',  'Michael',   'Jordan'),
  ('alice.wonder@citymail.cuny.edu',   'hashedpassword4',  'Alice',     'Wonderland'),
  ('bruce.wayne@citymail.cuny.edu',    'hashedpassword5',  'Bruce',     'Wayne'),
  ('olivia.brown@citymail.cuny.edu',   'hashedpassword6',  'Olivia',    'Brown'),
  ('liam.jones@citymail.cuny.edu',     'hashedpassword7',  'Liam',      'Jones'),
  ('sophia.miller@citymail.cuny.edu',  'hashedpassword8',  'Sophia',    'Miller'),
  ('noah.davis@citymail.cuny.edu',     'hashedpassword9',  'Noah',      'Davis'),
  ('isabella.garcia@citymail.cuny.edu','hashedpassword10', 'Isabella',  'Garcia'),
  ('ethan.rodriguez@citymail.cuny.edu','hashedpassword11', 'Ethan',     'Rodriguez'),
  ('mia.wilson@citymail.cuny.edu',     'hashedpassword12', 'Mia',       'Wilson'),
  ('alexander.moore@citymail.cuny.edu','hashedpassword13', 'Alexander', 'Moore'),
  ('charlotte.taylor@citymail.cuny.edu','hashedpassword14','Charlotte', 'Taylor'),
  ('jack.anderson@citymail.cuny.edu',  'hashedpassword15', 'Jack',      'Anderson'),
  ('amelia.thomas@citymail.cuny.edu',  'hashedpassword16', 'Amelia',    'Thomas'),
  ('logan.jackson@citymail.cuny.edu',  'hashedpassword17', 'Logan',     'Jackson'),
  ('eva.white@citymail.cuny.edu',      'hashedpassword18', 'Eva',       'White'),
  ('lucas.harris@citymail.cuny.edu',   'hashedpassword19', 'Lucas',     'Harris'),
  ('harper.martin@citymail.cuny.edu',  'hashedpassword20', 'Harper',    'Martin');
